import 'dart:convert';

class CompModel {
  /// Unique ID Generated By Firebase Database.
  String compId;

  /// Name of Company
  String name;

  /// Logo Link of the company (Generated By Firebase Storage).
  String logo;

  /// Location Link.
  String location;

  /// Default Constructor
  /// Use with caution as all it's variables equals to null
  CompModel();

  /// Firebase Database Constructor
  /// Commonly used when retrieving data from Firebase Database,
  /// or Any Provider that returns JSON/Map.
  CompModel.fromFDatabase(this.compId, Map json) {
    assert(json != null); // Stop executing if returned data corrupted.

    // splitting our json into the corresponding variables.
    name = json['name'];
    logo = json['logo'];
    location = json['location'];
  }

  /// function encodes the variables as A Json String (AKA. Stringify).
  ///
  /// inputs: None.
  /// Outputs : String/Json
  String toJson() {
    return json.encode({
      "name": name,
      "logo": logo,
      "location": location,
    });
  }
}
