import 'dart:convert';

class UserModel {
  /// Unique ID Generated By Firebase Database.
  String userId;

  /// Name of User
  String name;

  /// Email of User
  String email;

  /// Phone of User
  String phone;

  /// Default Constructor
  /// Use with caution as all it's variables equals to null
  UserModel();

  /// Firebase Database Constructor
  /// Commonly used when retrieving data from Firebase Database,
  /// or Any Provider that returns JSON/Map.
  UserModel.fromFDatabase(this.userId, Map json) {
    assert(json != null); // Stop executing if returned data corrupted.

    // splitting our json into the corresponding variables.
    name = json['name'];
    email = json['email'];
    phone = json['phone'];
  }

  /// function encodes the variables as A Json String (AKA. Stringify).
  ///
  /// inputs: None.
  /// Outputs : String/Json
  toJson() {
    return json.encode({
      "name": name,
      "email": email,
      "phone": phone,
    });
  }
}
